### ISSUE TITLE
How to encrypt a field from nested array

### ISSUE THREAD

**Issue by sh-muzzammil** [deliciousinsights/mongoose-pii#40]
{
   "_id":"5f841438366150038e3c6840",
   "createdOn":"2020-10-09T18:53:47.924+05:00",
   "recipientType":"Customer",
   "recipients":[
      {
         "_id":"5f8414383661502db23c6841",
         "receiver":"muzzammilsheikh1@gmail.com"
      },
      {
         "_id":"5f8414383661502db23c6841",
         "receiver":"muzzammilsheikh@gmail.com"
      }
   ],
   "__v":0
}

I want to encrypt and decrypt receiver email address from the same data above .. Its inside array

This is what my code looks like 

const recipientsModel = new mongoose.Schema({
  _memberId: {
    type: mongoose.Types.ObjectId,
  },
  receiver: {
    type: String,
  },
});

const processedTemplateModel = new mongoose.Schema({
  recipientType: {
    type: String,
    required: true,
  },
  recipients: {
    type: [recipientsModel,
    ],
  },
  createdOn: {
    type: Date,
    default: new Date(),
  },
});

recipientsModel.plugin(markFieldsAsPII, {
  fields: ['receiver'],
  key: process.env.MONGOOSE_PII_KEY,
});

processedTemplateModel.plugin(markFieldsAsPII, {
  fields: ['recipients.receiver'],
  key: process.env.MONGOOSE_PII_KEY,
});

const getProcessedTemplateModel = (tenantId?: String) => {
  return new MultiTenancy(tenantId).getTenantModel<IProcessedTemplate>(
    'ProcessedTemplateMuzz',
    processedTemplateModel,
    'processedtemplates_muzz',
  );
};

This is how i am trying to display decrypted emails 
 const templates = await getProcessedTemplateModel().find();

It is encrypting but not decrypting .. Can anyone help

**Comment by tdd** [comment]
Hey there!

I'm afraid the logic for identifying encrypted fields, especially on read, didn't take into account nested fields, be they inside arrays or single nested objects.

We unfortunately do not have time to maintain this anymore, but you should know that [MongoDB supports client-side encryption natively now](https://docs.mongodb.com/drivers/security/client-side-field-level-encryption-guide/) (since 4.2, hoping you're on a recent-enough instance; Enterprise is only required for "automatic encryption"), and that depending on your threat models, server-side, at-rest encryption may be a nicer solution (as it preserves all your querying logic, for instance).

Hoping this helps,

**Comment by sh-muzzammil** [comment]
thanks @tdd  : i achieved this through 

recipientsModel.plugin(markFieldsAsPII, {
  fields: ['receiver'],
  key: process.env.MONGOOSE_PII_KEY,
});

processedTemplateModel.plugin(markFieldsAsPII, {
  fields: [''],
  key: process.env.MONGOOSE_PII_KEY,
});

const getProcessedTemplateModel = (tenantId?: String) => {
  return new MultiTenancy(tenantId).getTenantModel<IProcessedTemplate>(
    'ProcessedTemplateMuzz',
    processedTemplateModel,
    'processedtemplates_muzz',
  );
};


Hope it helps anyone who is having this issue

**Comment by sh-muzzammil** [comment]
I have mentioned the solution above
